reports:
  - text: Contact Reports
    qtip: Reports associated with Persons and Groups
    iconCls: folder
    leaf: false
    children:
      - text: LCC Steering Committee
        url: ../alccsteeringcommittee
        qtip: Lists members of the LCC Steering Committee
        cols:
          - {text: First, dataIndex: firstname}
          - {text: Last, dataIndex: lastname}
          - {text: Primary Group, dataIndex: prigroupname, flex: 2}
          - {text: E-mail, dataIndex: priemail, flex: 1}
          - {text: Phone, columns: [{text: Area Code, dataIndex: priareacode},{text: Number, dataIndex: priphnumber},{text: Ext, dataIndex: priextension}]}
          - {text: Position, dataIndex: title, flex: 1}
        fields: [firstname, lastname, prigroupname, priemail, priareacode, priphnumber, priextension, title]
        filterBar: true
        limit: 40
        pbarPlugins:
          - type: Ext.ux.grid.GrabField
            cfg: {text: e-mail, dataindex: priemail, iconCls: pts-menu-email, tooltip: Get all visible e-mail addresses, delimiter: ", \n", windowTitle: E-mail addresses}
      - text: Project Admins
        url: ../projectadmin
        qtip: Contacts serving in an admin role for projects (i.e. Financial Officer, Primary Contact, Principal Investigator, Grants Admin).
        cols:
          - {text: First, dataIndex: firstname}
          - {text: Last, dataIndex: lastname}
          - {text: Primary Group, dataIndex: prigroupname, flex: 2}
          - {text: E-mail, dataIndex: priemail, flex: 1}
          - {text: Phone, columns: [{text: Area Code, dataIndex: priareacode},{text: Number, dataIndex: priphnumber},{text: Ext, dataIndex: priextension}]}
          - {text: Project Active?, dataIndex: active}
        fields: [firstname, lastname, prigroupname, priemail, priareacode, priphnumber, priextension, {name: active, type: string}]
        filterBar: true
        limit: 30
        pbarPlugins:
          - type: Ext.ux.grid.GrabField
            cfg: {text: e-mail, dataindex: priemail, iconCls: pts-menu-email, tooltip: Get all visible e-mail addresses, delimiter: ", \n", windowTitle: E-mail addresses}
      - text: LCC Staff
        url: ../alccstaff
        qtip: Lists staff of the LCC
        cols:
          - {text: First, dataIndex: firstname}
          - {text: Last, dataIndex: lastname}
        fields: [firstname, lastname]
  - text: Project Reports
    qtip: Reports associated with Projects
    iconCls: folder
    leaf: false
    children:
      - text: Short Project Summary
        url: ../shortprojectsummary
        qtip: Lists projectcode, title, shorttitle, PIs, startdate, enddate, description, abstract
        cols:
          - {text: Project, dataIndex: projectcode}
          - {text: Status, dataIndex: status}
          - {text: Principal Investigators, dataIndex: principalinvestigators, flex: 1}
          - {text: Title, dataIndex: title, flex: 1}
          - {text: Short Title, dataIndex: shorttitle, hidden: true}
          - {text: Description, dataIndex: description, flex: 2}
          - {text: Abstract, dataIndex: abstract, flex: 2, hidden:true}
        fields: [projectcode, status, principalinvestigators, shorttitle, title, startdate, enddate, description, abstract]
      - text: Long Project Summary
        url: ../longprojectsummary
        qtip: Lists projectcode, title, shorttitle, PIs, startdate, enddate, description, abstract, funding
        cols:
          - {text: Project, dataIndex: projectcode}
          - {text: UUID, dataIndex: uuid, hidden: true}
          - {text: Status, dataIndex: status, hidden: true}
          - {text: Start, dataIndex: startdate, hidden: true}
          - {text: End, dataIndex: enddate}
          - {text: Principal Investigators, dataIndex: principalinvestigators, flex: 1}
          - {text: Title, dataIndex: title, flex: 1}
          - {text: Short Title, dataIndex: shorttitle, hidden: true}
          - {text: Description, dataIndex: description, flex: 2}
          - {text: Abstract, dataIndex: abstract, flex: 2, hidden:true}
          - {text: Allocated, dataIndex: allocated, renderer: usMoney}
          - {text: Invoiced, dataIndex: invoiced, renderer: usMoney}
          - {text: Difference, dataIndex: difference, renderer: usMoney}
          - {text: Leveraged, dataIndex: leveraged, renderer: usMoney}
          - {text: Total, dataIndex: total, renderer: usMoney}
        fields: [projectcode, uuid, status, principalinvestigators, shorttitle, title, startdate, enddate, description, abstract, allocated, invoiced, difference, leveraged, total]
      - text: Project Keywords
        url: ../projectkeywords
        qtip: Lists keywords for each project
        cols:
          - {text: Project, dataIndex: projectcode}
          - {text: Short Title, dataIndex: shorttitle, flex: 1}
          - {text: Keywords, dataIndex: keywords, flex: 2}
          - {text: Joined Keywords, dataIndex: joined, flex: 2, hidden: true}
        fields: [projectcode, shorttitle, keywords, joined]
        pbarPlugins:
          - type: Ext.ux.grid.GrabField
            cfg: {text: Keywords, iconCls: pts-menu-key, dataindex: keywords, tooltip: 'Get a list of all visible keywords', windowTitle: 'Project Keywords'}
      - text: Project Agreement Numbers
        url: ../projectagreementnumbers
        qtip: Lists agreement numbers for each project
        cols:
          - {text: Project, dataIndex: projectcode}
          - {text: Short Title, dataIndex: shorttitle, flex: 1}
          - {text: Agreement Number, dataIndex: agreementnumber, width: 150}
          - {text: Agreement Title, dataIndex: agreementtitle, flex: 2}
        fields: [projectcode, shorttitle, agreementnumber, agreementtitle]
      - text: National Project Catalog
        url: ../projectcatalog
        qtip: Data for reporting to the Simple National Project Catalog
        cols:
          - {text: LCC Name, dataIndex: lccname, flex: 1, hidden: true}
          - {text: Id, dataIndex: id, flex: 1, hidden: false}
          - {text: Project Title, dataIndex: ptitle, flex: 2, hidden: false}
          - {text: Description, dataIndex: description, flex: 1, hidden: true}
          - {text: Status, dataIndex: pstatus, flex: 1, hidden: false}
          - {text: Start Date, dataIndex: pstart, flex: 1, hidden: false}
          - {text: End Date, dataIndex: pend, flex: 1, hidden: false}
          - {text: URL, dataIndex: purl, flex: 1, hidden: true}
          - {text: Project Lead, dataIndex: leadcontact, flex: 2, hidden: false}
          - {text: Lead Org, dataIndex: leadorg, flex: 2, hidden: false}
          - {text: Partner Org, dataIndex: partnerorg, flex: 2, hidden: false}
          - {text: Target Audience, dataIndex: endusers, flex: 1, hidden: true}
          - {text: Fiscal Year Allocation, dataIndex: fiscalyears, flex: 1, hidden: true}
          - {text: LCC Co-funding, dataIndex: cofundlcc1, flex: 1, hidden: true}
          - {text: LCC Co-funding, dataIndex: cofundlcc2, flex: 1, hidden: true}
          - {text: ScienceBase, dataIndex: scibaseq, flex: 1, hidden: true}
          - {text: Total LCC Funding, dataIndex: lccfundall, flex: 1, hidden: false}
          - {text: Funding Year/Source, dataIndex: lccfundby, flex: 2, hidden: false}
          - {text: Total Matching Funds, dataIndex: matchfundall, flex: 1, hidden: false}
          - {text: Matching Year/Source, dataIndex: matchfundby, flex: 2, hidden: false}
          - {text: Match Notes, dataIndex: matchfundnote, flex: 1, hidden: true}
          - {text: Primary Category, dataIndex: category1, flex: 1, hidden: true}
          - {text: Project Category, dataIndex: category2, flex: 1, hidden: true}
          - {text: Project Category, dataIndex: category3, flex: 1, hidden: true}
          - {text: Deliverable Type, dataIndex: deliver1, flex: 1, hidden: true}
          - {text: Deliverable Type, dataIndex: deliver2, flex: 1, hidden: true}
          - {text: Deliverable Type, dataIndex: deliver3, flex: 1, hidden: true}
          - {text: Subject Keywords, dataIndex: subject, flex: 1, hidden: true}
          - {text: Geographic Keywords, dataIndex: geog, flex: 1, hidden: true}
          - {text: Congress District, dataIndex: congdist, flex: 1, hidden: true}
          - {text: Comments, dataIndex: comments, flex: 1, hidden: true}
        fields: [lccname,id,ptitle,description,pstatus,pstart,pend,purl,leadcontact,leadorg,partnerorg,endusers,fiscalyears,cofundlcc1,cofundlcc2,scibaseq,lccfundall,lccfundby,matchfundall,matchfundby,matchfundnote,category1,category2,category3,deliver1,deliver2,deliver3,subject,geog,congdist,comments]
  - text: Deliverable Reports
    qtip: Reports associated with Deliverables
    iconCls: folder
    leaf: false
    children:
      - text: Overdue/Due Soon Deliverables
        url: ../noticesent
        qtip: Lists deliverables either overdue or due soon(30 days) and notice status
        cols:
          - {text: Due Date, dataIndex: duedate}
          - {text: Title, dataIndex: title, flex: 1}
          - {text: Description, dataIndex: description, flex: 2, hidden: false}
          - {text: Last Notice, dataIndex: lastnotice}
          - {text: Date Sent, dataIndex: datesent}
          - {text: Reporting Period, hidden:true, columns: [{text: Start, dataIndex: startdate, hidden: true, width: 70},{text: End, dataIndex: enddate, hidden: true, width: 70}]}
          - {text: Project, dataIndex: projectcode}
          - {text: Project Title, dataIndex: project, flex: 1}
          - {text: Pri. Investigator, dataIndex: contact, flex: 1}
          - {text: PI Email, dataIndex: email, flex: 1}
          - {text: Financial Officer, dataIndex: fofficer, flex: 1, hidden:true}
          - {text: FO Email, dataIndex: foemail, flex: 1, hidden:true}
          - {text: Past Due, dataIndex: dayspastdue, hidden:false}
          - {text: Status, dataIndex: status, hidden:false}
          - {text: Agreement, dataIndex: agreementnumber, hidden:false}
          - {text: Staff Comments, dataIndex: staffcomments, flex: 2, hidden:false}
        fields: [duedate, title, description, lastnotice, datesent, startdate, enddate, projectcode, project, contact, email, fofficer, foemail, dayspastdue, status, agreementnumber, staffcomments]
  - text: Funding Reports
    qtip: Reports detailing funding activity
    iconCls: folder
    leaf: false
    children:
      - text: Project Funding
        url: ../projectfunding
        qtip: Lists allocated, invoiced, leveraged, and total(allocated + leveraged) funding for each project.
        cols:
          - {text: Project, dataIndex: projectcode}
          - {text: Title, dataIndex: title, flex: 1}
          - {text: Short Title, dataIndex: shorttitle, hidden: true, flex: 1}
          - {text: Allocated, dataIndex: allocated, renderer: usMoney}
          - {text: Invoiced, dataIndex: invoiced, renderer: usMoney}
          - {text: Difference, dataIndex: difference, renderer: usMoney}
          - {text: Leveraged, dataIndex: leveraged, renderer: usMoney}
          - {text: Total, dataIndex: total, renderer: usMoney}
          - {text: Status, dataIndex: status, hidden:true}
        fields: [projectcode, fiscalyear, number, title, shorttitle, {name: allocated, type: number}, invoiced, difference, leveraged, total, status]
