reports:
  - text: Contact Reports
    descrip: Reports associated with Persons and Groups
    iconCls: folder
    leaf: false
    children:
      - text: ALCC Steering Committee
        url: ../alccsteeringcommittee
        descrip: Lists members of the ALCC Steering Committee
        xtype: personlist
        model: PTS.model.Person
        pbarPlugins:
          - type: Ext.ux.grid.GrabField
            cfg: {text: e-mail, dataindex: priemail}
      - text: ALCC Staff
        url: ../alccstaff
        descrip: Lists staff of the ALCC
        cols:
          - {text: First, dataIndex: firstname}
          - {text: Last, dataIndex: lastname}
        fields: [firstname, lastname]
  - text: Project Reports
    descrip: Reports associated with Projects
    iconCls: folder
    leaf: false
    children:
      - text: Short Project Summary
        url: ../shortprojectsummary
        descrip: Lists projectcode, title, shorttitle, PIs, startdate, enddate, description, abstract
        cols:
          - {text: Project, dataIndex: projectcode}
          - {text: Status, dataIndex: status}
          - {text: Principal Investigators, dataIndex: principalinvestigators, flex: 1}
          - {text: Title, dataIndex: title, flex: 1}
          - {text: Short Title, dataIndex: shorttitle, hidden: true}
          - {text: Description, dataIndex: description, flex: 2}
          - {text: Abstract, dataIndex: abstract, flex: 2, hidden:true}
        fields: [projectcode, status, principalinvestigators, shorttitle, title, startdate, enddate, description, abstract]
      - text: Project Keywords
        url: ../projectkeywords
        descrip: Lists keywords for each project
        cols:
          - {text: Project, dataIndex: projectcode}
          - {text: Short Title, dataIndex: shorttitle, flex: 1}
          - {text: Keywords, dataIndex: keywords, flex: 2}
          - {text: Joined Keywords, dataIndex: joined, flex: 2, hidden: true}
        fields: [projectcode, shorttitle, keywords, joined]
        pbarPlugins:
          - type: Ext.ux.grid.GrabField
            cfg: {text: Keywords, iconCls: pts-menu-key, dataindex: keywords, tooltip: 'Get a list of all visible keywords', windowTitle: 'Project Keywords'}
      - text: Project Agreement Numbers
        url: ../projectagreementnumbers
        descrip: Lists agreement numbers for each project
        cols:
          - {text: Project, dataIndex: projectcode}
          - {text: Short Title, dataIndex: shorttitle, flex: 1}
          - {text: Agreement Number, dataIndex: agreementnumber, width: 150}
          - {text: Agreement Title, dataIndex: agreementtitle, flex: 2}
        fields: [projectcode, shorttitle, agreementnumber, agreementtitle]
  - text: Deliverable Reports
    descrip: Reports associated with Deliverables
    iconCls: folder
    leaf: false
    children:
      - text: Deliverable Notices
        url: ../noticesent
        descrip: Lists deliverables either overdue or due soon(30 days) and notice status
        cols:
          - {text: Due Date, dataIndex: duedate}
          - {text: Title, dataIndex: title, flex: 1}
          - {text: Description, dataIndex: description, flex: 2, hidden: true}
          - {text: Last Notice, dataIndex: lastnotice}
          - {text: Date Sent, dataIndex: datesent}
          - {text: Project, dataIndex: projectcode}
          - {text: Project Title, dataIndex: project, flex: 1}
          - {text: Pri. Investigator, dataIndex: contact, flex: 1}
          - {text: PI Email, dataIndex: email, flex: 1}
          - {text: Financial Officer, dataIndex: fofficer, flex: 1}
          - {text: FO Email, dataIndex: foemail, flex: 1}
          - {text: Past Due, dataIndex: dayspastdue, hidden:true}
          - {text: Status, dataIndex: status, hidden:true}
        fields: [duedate, title, description, lastnotice, datesent, projectcode, project, contact, email, fofficer, foemail, dayspastdue, status]
  - text: Funding Reports
    descrip: Reports detailing funding activity
    iconCls: folder
    leaf: false
    children:
      - text: Project Funding
        url: ../projectfunding
        descrip: Lists allocated, invoiced, leveraged, and total(allocated + leveraged) funding for each project.
        cols:
          - {text: Project, dataIndex: projectcode}
          - {text: Title, dataIndex: title, flex: 1}
          - {text: Short Title, dataIndex: shorttitle, hidden: true, flex: 1}
          - {text: Allocated, dataIndex: allocated, renderer: usMoney}
          - {text: Invoiced, dataIndex: invoiced, renderer: usMoney}
          - {text: Difference, dataIndex: difference, renderer: usMoney}
          - {text: Leveraged, dataIndex: leveraged, renderer: usMoney}
          - {text: Total, dataIndex: total, renderer: usMoney}
          - {text: Status, dataIndex: status, hidden:true}
        fields: [projectcode, fiscalyear, number, title, shorttitle, {name: allocated, type: number}, invoiced, difference, leveraged, total, status]
